baseURL = "https://www.creaturelove7.com/"
title = "David Zhang"
theme = "PaperMod"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
  author = "David Zhang"
  mainSections = ["ai", "books", "tech", "career"]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  defaultTheme = "auto"
  displayFullLangName = true
  comments = true

  [params.subscribe]
    endpoint = "https://email-beta-six.vercel.app/api/subscribe"

  [params.giscus]
    repo = "scinttt/my-blog"
    repoID = "R_kgDORLy8Qg"
    category = "Announcements"
    categoryID = "DIC_kwDORLy8Qs4C6FB1"
    mapping = "pathname"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "top"
    lang = "en"

  [params.cusdis]
    appId = "e2b52649-cf5d-45ba-a846-f523c1c049e3"
    host = "https://cusdis.com"

  [params.assets]
    favicon = "favicon.svg"
    favicon16x16 = "favicon-16x16.png"
    favicon32x32 = "favicon-32x32.png"
    apple_touch_icon = "apple-touch-icon.png"
    safari_pinned_tab = "safari-pinned-tab.svg"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    codeFences = true
    lineNos = true
    style = "monokai"

[related]
  includeNewer = true
  threshold = 50
  toLower = true
  [[related.indices]]
    name = "tags"
    weight = 100

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-US"
    weight = 1
    [languages.en.params]
      description = "Tech | Career | AI | Books"
    [[languages.en.menu.main]]
      name = "Latest"
      pageRef = "/"
      weight = 1
    [[languages.en.menu.main]]
      name = "Tech"
      pageRef = "/tech"
      weight = 2
    [[languages.en.menu.main]]
      name = "Career"
      pageRef = "/career"
      weight = 3
    [[languages.en.menu.main]]
      name = "AI"
      pageRef = "/ai"
      weight = 4
    [[languages.en.menu.main]]
      name = "Books"
      pageRef = "/books"
      weight = 5
  [languages.zh]
    languageName = "中文"
    languageCode = "zh-CN"
    weight = 2
    [languages.zh.params]
      description = "技术 | 职业 | AI | 读书"
    [[languages.zh.menu.main]]
      name = "最新"
      pageRef = "/"
      weight = 1
    [[languages.zh.menu.main]]
      name = "技术"
      pageRef = "/tech"
      weight = 2
    [[languages.zh.menu.main]]
      name = "职业"
      pageRef = "/career"
      weight = 3
    [[languages.zh.menu.main]]
      name = "AI"
      pageRef = "/ai"
      weight = 4
    [[languages.zh.menu.main]]
      name = "读书"
      pageRef = "/books"
      weight = 5
