baseURL = "https://www.creaturelove7.com/"
title = "Renren Zhang"
theme = "PaperMod"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
  author = "Renren Zhang"
  mainSections = ["ai", "books", "tech", "money", "career"]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  defaultTheme = "auto"
  displayFullLangName = true

  [params.subscribe]
    endpoint = ""

  [params.assets]
    favicon = "favicon.svg"
    favicon16x16 = "favicon-16x16.png"
    favicon32x32 = "favicon-32x32.png"
    apple_touch_icon = "apple-touch-icon.png"
    safari_pinned_tab = "safari-pinned-tab.svg"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    codeFences = true
    lineNos = true
    style = "monokai"

[related]
  includeNewer = true
  threshold = 50
  toLower = true
  [[related.indices]]
    name = "tags"
    weight = 100

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-US"
    weight = 1
    [languages.en.params]
      description = "Tech | Career | AI | Books | Money"
    [[languages.en.menu.main]]
      name = "Home"
      pageRef = "/"
      weight = 1
    [[languages.en.menu.main]]
      name = "Tech"
      pageRef = "/tech"
      weight = 2
    [[languages.en.menu.main]]
      name = "Career"
      pageRef = "/career"
      weight = 3
    [[languages.en.menu.main]]
      name = "AI"
      pageRef = "/ai"
      weight = 4
    [[languages.en.menu.main]]
      name = "Books"
      pageRef = "/books"
      weight = 5
    [[languages.en.menu.main]]
      name = "Money"
      pageRef = "/money"
      weight = 6

  [languages.zh]
    languageName = "中文"
    languageCode = "zh-CN"
    weight = 2
    [languages.zh.params]
      description = "技术 | 职业 | AI | 读书 | 理财"
    [[languages.zh.menu.main]]
      name = "主页"
      pageRef = "/"
      weight = 1
    [[languages.zh.menu.main]]
      name = "技术"
      pageRef = "/tech"
      weight = 2
    [[languages.zh.menu.main]]
      name = "职业"
      pageRef = "/career"
      weight = 3
    [[languages.zh.menu.main]]
      name = "AI"
      pageRef = "/ai"
      weight = 4
    [[languages.zh.menu.main]]
      name = "读书"
      pageRef = "/books"
      weight = 5
    [[languages.zh.menu.main]]
      name = "理财"
      pageRef = "/money"
      weight = 6
